name: Run Terraform commands

on:
  push:
    branches:
    - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Run terraform fmt
      uses: dflook/terraform-fmt@v1
      with:
        path: .

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
    - name: Run terraform validate
      uses: dflook/terraform-validate@v1
      with:
        path: .